function RunAllGenesFile

load 'AllGenes';
load 'GeneOntology';

N=size(means, 1);
SaveAnnotatedGeneFile([1:N], ...
		  psGeneSymbols, ...
		  psTitles, ...
		  psEntrezIDs, ...
		  psNames, ...
		  'AllGenes.tsv', ...
		  psGOProcess, ...
		  psGOComponent, ...
		  psGOFunction, ...
		  goTerms, ...
		  means, ...
		  stdDevs, ...
		  uniqueExptNames, ...
		  numReplicates, ...
		  [], ...
		  {});

		  