function RunDiffExpTFGenesFile

load 'DiffExpTFGenes';
load 'GeneOntology';

N=size(means, 1);
tfClust = GetClusterForGenes(psGeneSymbols);
SaveAnnotatedGeneFile([1:N], ...
		  psGeneSymbols, ...
		  psTitles, ...
		  psEntrezIDs, ...
		  psNames, ...
		  'DiffExpTFGenes.tsv', ...
		  psGOProcess, ...
		  psGOComponent, ...
		  psGOFunction, ...
		  goTerms, ...
		  means, ...
		  stdDevs, ...
		  uniqueExptNames, ...
		  numReplicates, ...
		  [], ...
		  {}, ...
                  tfClust);

		  