function RunGOAnalysisFile

load 'GOAnalysis';
load GeneOntology 'ontNames' 'ontCode';

G = length(diffExpGO);

fid=fopen('GOAnalysis.tsv','w+');
fprintf(fid, 'Cluster\tGOID\tGO Term\tOnt Name\tlog PV\tont level\tcount\tsuper freq\tsmall freq\n');
for g=1:G
  goSt = diffExpGO{g};
  goid = goSt{1};
  fprintf(fid, '%d\tGO:%0.7d\t%s\t%s\t%f\t%d\t%d\t%f\t%f\n', ...
	  0, ...
	  goSt{1}, ...
	  goSt{2}, ...
          ontNames{ontCode(goid)}, ...
	  goSt{3}, ...
	  goSt{4}, ...
	  goSt{5}, ...
	  goSt{6}, ...
	  goSt{7});
end

C = length(clustGO);
for c=1:C
  cgo = clustGO{c};
  G = length(cgo);
  for g=1:G
    goSt = cgo{g};
    if length(goSt) > 0
      goid = goSt{1};
      fprintf(fid, '%d\tGO:%0.7d\t%s\t%s\t%f\t%d\t%d\t%f\t%f\n', ...
	      c, ...
	      goSt{1}, ...
	      goSt{2}, ...
              ontNames{ontCode(goid)}, ...
	      goSt{3}, ...
	      goSt{4}, ...
	      goSt{5}, ...
	      goSt{6}, ...
	      goSt{7});
    end
  end
end

fclose(fid);
