function [map] = TFClustMatrixCmap(csize)
% /VOLUMES/SRAMSEY/PROJECTS/MACNET/MATLAB/SCRIPTS/TFCLUSTMATRIXCMAP - Colormap
%   usage: /Volumes/sramsey/Projects/MacNet/Matlab/Scripts/TFClustMatrixCmap - returns a colormap the same length as the
%               current figure's colormap.
%          /Volumes/sramsey/Projects/MacNet/Matlab/Scripts/TFClustMatrixCmap(M) - returns an M x 3 sized colormap.
% 

% This m-file was automatically generated by makecmap.m
% Date: 18-Jun-2007 13:12:21

if nargin < 1
  csize = size(get(gcf,'Colormap'),1);
end

nodes = [ 1.562500e-02	0.000000e+00;...
          5.000000e-01	0.000000e+00;...
          1.000000e+00	1.000000e+00];
nodes(:,1) = round(nodes(:,1)*csize);
nodes(1,1) = 1;
for i = 1:size(nodes,1)-1
  W = lspace(nodes(i,2),nodes(i+1,2),nodes(i+1,1)-nodes(i, 1)+1);
  map(1,nodes(i,1):nodes(i+1,1)-1) = W(1:nodes(i+1,1)- nodes(i,1));
end
map(1,nodes(i+1,1)) = nodes(i+1,2);

nodes = [ 1.562500e-02	5.028736e-01;...
          5.000000e-01	0.000000e+00;...
          1.000000e+00	5.028736e-01];
nodes(:,1) = round(nodes(:,1)*csize);
nodes(1,1) = 1;
for i = 1:size(nodes,1)-1
  W = lspace(nodes(i,2),nodes(i+1,2),nodes(i+1,1)-nodes(i, 1)+1);
  map(2,nodes(i,1):nodes(i+1,1)-1) = W(1:nodes(i+1,1)- nodes(i,1));
end
map(2,nodes(i+1,1)) = nodes(i+1,2);

nodes = [ 1.562500e-02	1.000000e+00;...
          5.000000e-01	2.873563e-03;...
          1.000000e+00	0.000000e+00];
nodes(:,1) = round(nodes(:,1)*csize);
nodes(1,1) = 1;
for i = 1:size(nodes,1)-1
  W = lspace(nodes(i,2),nodes(i+1,2),nodes(i+1,1)-nodes(i, 1)+1);
  map(3,nodes(i,1):nodes(i+1,1)-1) = W(1:nodes(i+1,1)- nodes(i,1));
end
map(3,nodes(i+1,1)) = nodes(i+1,2);

nodes = [ 1.562500e-02	1.000000e+00;...
          1.000000e+00	1.000000e+00];
nodes(:,1) = round(nodes(:,1)*csize);
nodes(1,1) = 1;
for i = 1:size(nodes,1)-1
  W = lspace(nodes(i,2),nodes(i+1,2),nodes(i+1,1)-nodes(i, 1)+1);
  map(4,nodes(i,1):nodes(i+1,1)-1) = W(1:nodes(i+1,1)- nodes(i,1));
end
map(4,nodes(i+1,1)) = nodes(i+1,2);

map = (map(1:3,:) .* repmat(map(4,:),3,1))';

% ----------------------------
function out = lspace(x,y,N)
out = [x+(0:N-2)*(y-x)/(N-1) y];
